amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    laser_model_type: "likelihood_field"
    min_particles: 500
    max_particles: 2000
    transform_tolerance: 1.0
    scan_topic: scan
    z_hit: 0.5
    z_rand: 0.5
    z_max: 0.05
    z_short: 0.05

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_footprint
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      allow_unknown: true

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

# --- COMMENTED OUT NON-ESSENTIAL PARTS ---
# amcl_map_client:
#   ros__parameters:
#     use_sim_time: True

# amcl_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

# controller_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

# local_costmap_client:
#   ros__parameters:
#     use_sim_time: True

# local_costmap_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

# global_costmap_client:
#   ros__parameters:
#     use_sim_time: True

# global_costmap_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

# recoveries_server:
#   ros__parameters:
#     use_sim_time: true
#     recovery_plugins: ["spin", "back_up", "wait"]
#     spin:
#       plugin: "nav2_behaviors/SpinBehavior"
#     back_up:
#       plugin: "nav2_behaviors/BackUpBehavior"
#     wait:
#       plugin: "nav2_behaviors/WaitBehavior"

# map_saver:
#   ros__parameters:
#     use_sim_time: True

# robot_state_publisher:
#   ros__parameters:
#     use_sim_time: True
